package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CategorieProduit generated by hbm2java
 */
public class CategorieProduit  implements java.io.Serializable {


     private Integer idCategorieProduit;
     private String categorieProduit;
     private Set sousCategorieProduits = new HashSet(0);

    public CategorieProduit() {
    }

	
    public CategorieProduit(String categorieProduit) {
        this.categorieProduit = categorieProduit;
    }
    public CategorieProduit(String categorieProduit, Set sousCategorieProduits) {
       this.categorieProduit = categorieProduit;
       this.sousCategorieProduits = sousCategorieProduits;
    }
   
    public Integer getIdCategorieProduit() {
        return this.idCategorieProduit;
    }
    
    public void setIdCategorieProduit(Integer idCategorieProduit) {
        this.idCategorieProduit = idCategorieProduit;
    }
    public String getCategorieProduit() {
        return this.categorieProduit;
    }
    
    public void setCategorieProduit(String categorieProduit) {
        this.categorieProduit = categorieProduit;
    }
    public Set getSousCategorieProduits() {
        return this.sousCategorieProduits;
    }
    
    public void setSousCategorieProduits(Set sousCategorieProduits) {
        this.sousCategorieProduits = sousCategorieProduits;
    }




}


