package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * CategorieClient generated by hbm2java
 */
public class CategorieClient  implements java.io.Serializable {


     private Integer idCategorieClient;
     private String categorieClient;
     private Set clients = new HashSet(0);

    public CategorieClient() {
    }

	
    public CategorieClient(String categorieClient) {
        this.categorieClient = categorieClient;
    }
    public CategorieClient(String categorieClient, Set clients) {
       this.categorieClient = categorieClient;
       this.clients = clients;
    }
   
    public Integer getIdCategorieClient() {
        return this.idCategorieClient;
    }
    
    public void setIdCategorieClient(Integer idCategorieClient) {
        this.idCategorieClient = idCategorieClient;
    }
    public String getCategorieClient() {
        return this.categorieClient;
    }
    
    public void setCategorieClient(String categorieClient) {
        this.categorieClient = categorieClient;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


