package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private CategorieClient categorieClient;
     private Ville ville;
     private String nomClient;
     private String prenomClient;
     private String telephoneClient;
     private String emailClient;
     private String adresseClient;
     private Float latitudeClient;
     private Float longitudeClient;
     private String pseudoClient;
     private String mdpClient;
     private Short visibiliteInfos;
     private String siretClient;
     private Set produitsForCliIdClient = new HashSet(0);
     private Set produitsForIdClient = new HashSet(0);

    public Client() {
    }

	
    public Client(CategorieClient categorieClient, Ville ville, String nomClient, String emailClient, String adresseClient, String pseudoClient, String mdpClient) {
        this.categorieClient = categorieClient;
        this.ville = ville;
        this.nomClient = nomClient;
        this.emailClient = emailClient;
        this.adresseClient = adresseClient;
        this.pseudoClient = pseudoClient;
        this.mdpClient = mdpClient;
    }
    public Client(CategorieClient categorieClient, Ville ville, String nomClient, String prenomClient, String telephoneClient, String emailClient, String adresseClient, Float latitudeClient, Float longitudeClient, String pseudoClient, String mdpClient, Short visibiliteInfos, String siretClient, Set produitsForCliIdClient, Set produitsForIdClient) {
       this.categorieClient = categorieClient;
       this.ville = ville;
       this.nomClient = nomClient;
       this.prenomClient = prenomClient;
       this.telephoneClient = telephoneClient;
       this.emailClient = emailClient;
       this.adresseClient = adresseClient;
       this.latitudeClient = latitudeClient;
       this.longitudeClient = longitudeClient;
       this.pseudoClient = pseudoClient;
       this.mdpClient = mdpClient;
       this.visibiliteInfos = visibiliteInfos;
       this.siretClient = siretClient;
       this.produitsForCliIdClient = produitsForCliIdClient;
       this.produitsForIdClient = produitsForIdClient;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public CategorieClient getCategorieClient() {
        return this.categorieClient;
    }
    
    public void setCategorieClient(CategorieClient categorieClient) {
        this.categorieClient = categorieClient;
    }
    public Ville getVille() {
        return this.ville;
    }
    
    public void setVille(Ville ville) {
        this.ville = ville;
    }
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }
    public String getPrenomClient() {
        return this.prenomClient;
    }
    
    public void setPrenomClient(String prenomClient) {
        this.prenomClient = prenomClient;
    }
    public String getTelephoneClient() {
        return this.telephoneClient;
    }
    
    public void setTelephoneClient(String telephoneClient) {
        this.telephoneClient = telephoneClient;
    }
    public String getEmailClient() {
        return this.emailClient;
    }
    
    public void setEmailClient(String emailClient) {
        this.emailClient = emailClient;
    }
    public String getAdresseClient() {
        return this.adresseClient;
    }
    
    public void setAdresseClient(String adresseClient) {
        this.adresseClient = adresseClient;
    }
    public Float getLatitudeClient() {
        return this.latitudeClient;
    }
    
    public void setLatitudeClient(Float latitudeClient) {
        this.latitudeClient = latitudeClient;
    }
    public Float getLongitudeClient() {
        return this.longitudeClient;
    }
    
    public void setLongitudeClient(Float longitudeClient) {
        this.longitudeClient = longitudeClient;
    }
    public String getPseudoClient() {
        return this.pseudoClient;
    }
    
    public void setPseudoClient(String pseudoClient) {
        this.pseudoClient = pseudoClient;
    }
    public String getMdpClient() {
        return this.mdpClient;
    }
    
    public void setMdpClient(String mdpClient) {
        this.mdpClient = mdpClient;
    }
    public Short getVisibiliteInfos() {
        return this.visibiliteInfos;
    }
    
    public void setVisibiliteInfos(Short visibiliteInfos) {
        this.visibiliteInfos = visibiliteInfos;
    }
    public String getSiretClient() {
        return this.siretClient;
    }
    
    public void setSiretClient(String siretClient) {
        this.siretClient = siretClient;
    }
    public Set getProduitsForCliIdClient() {
        return this.produitsForCliIdClient;
    }
    
    public void setProduitsForCliIdClient(Set produitsForCliIdClient) {
        this.produitsForCliIdClient = produitsForCliIdClient;
    }
    public Set getProduitsForIdClient() {
        return this.produitsForIdClient;
    }
    
    public void setProduitsForIdClient(Set produitsForIdClient) {
        this.produitsForIdClient = produitsForIdClient;
    }




}


