package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Departement generated by hbm2java
 */
public class Departement  implements java.io.Serializable {


     private Integer idDepartement;
     private Region region;
     private String codeDepartement;
     private String nomDepartement;
     private Set villes = new HashSet(0);

    public Departement() {
    }

	
    public Departement(Region region, String codeDepartement, String nomDepartement) {
        this.region = region;
        this.codeDepartement = codeDepartement;
        this.nomDepartement = nomDepartement;
    }
    public Departement(Region region, String codeDepartement, String nomDepartement, Set villes) {
       this.region = region;
       this.codeDepartement = codeDepartement;
       this.nomDepartement = nomDepartement;
       this.villes = villes;
    }
   
    public Integer getIdDepartement() {
        return this.idDepartement;
    }
    
    public void setIdDepartement(Integer idDepartement) {
        this.idDepartement = idDepartement;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getCodeDepartement() {
        return this.codeDepartement;
    }
    
    public void setCodeDepartement(String codeDepartement) {
        this.codeDepartement = codeDepartement;
    }
    public String getNomDepartement() {
        return this.nomDepartement;
    }
    
    public void setNomDepartement(String nomDepartement) {
        this.nomDepartement = nomDepartement;
    }
    public Set getVilles() {
        return this.villes;
    }
    
    public void setVilles(Set villes) {
        this.villes = villes;
    }




}


