package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays  implements java.io.Serializable {


     private Integer idPays;
     private String nomPays;
     private String codePays;
     private String codeIso3Pays;
     private Set regions = new HashSet(0);

    public Pays() {
    }

	
    public Pays(String nomPays, String codePays, String codeIso3Pays) {
        this.nomPays = nomPays;
        this.codePays = codePays;
        this.codeIso3Pays = codeIso3Pays;
    }
    public Pays(String nomPays, String codePays, String codeIso3Pays, Set regions) {
       this.nomPays = nomPays;
       this.codePays = codePays;
       this.codeIso3Pays = codeIso3Pays;
       this.regions = regions;
    }
   
    public Integer getIdPays() {
        return this.idPays;
    }
    
    public void setIdPays(Integer idPays) {
        this.idPays = idPays;
    }
    public String getNomPays() {
        return this.nomPays;
    }
    
    public void setNomPays(String nomPays) {
        this.nomPays = nomPays;
    }
    public String getCodePays() {
        return this.codePays;
    }
    
    public void setCodePays(String codePays) {
        this.codePays = codePays;
    }
    public String getCodeIso3Pays() {
        return this.codeIso3Pays;
    }
    
    public void setCodeIso3Pays(String codeIso3Pays) {
        this.codeIso3Pays = codeIso3Pays;
    }
    public Set getRegions() {
        return this.regions;
    }
    
    public void setRegions(Set regions) {
        this.regions = regions;
    }




}


