package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Produit generated by hbm2java
 */
public class Produit  implements java.io.Serializable {


     private Integer idProduit;
     private Client clientByCliIdClient;
     private SousCategorieProduit sousCategorieProduit;
     private Client clientByIdClient;
     private String designationProduit;
     private float prixProduit;
     private Date dateMiseEnVenteProduit;
     private String descriptionProduit;

    public Produit() {
    }

	
    public Produit(SousCategorieProduit sousCategorieProduit, String designationProduit, float prixProduit, Date dateMiseEnVenteProduit) {
        this.sousCategorieProduit = sousCategorieProduit;
        this.designationProduit = designationProduit;
        this.prixProduit = prixProduit;
        this.dateMiseEnVenteProduit = dateMiseEnVenteProduit;
    }
    public Produit(Client clientByCliIdClient, SousCategorieProduit sousCategorieProduit, String designationProduit, float prixProduit, Date dateMiseEnVenteProduit, String descriptionProduit) {
       this.clientByCliIdClient = clientByCliIdClient;
       this.sousCategorieProduit = sousCategorieProduit;
       this.designationProduit = designationProduit;
       this.prixProduit = prixProduit;
       this.dateMiseEnVenteProduit = dateMiseEnVenteProduit;
       this.descriptionProduit = descriptionProduit;
    }
   
    public Integer getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(Integer idProduit) {
        this.idProduit = idProduit;
    }
    public Client getClientByCliIdClient() {
        return this.clientByCliIdClient;
    }
    
    public void setClientByCliIdClient(Client clientByCliIdClient) {
        this.clientByCliIdClient = clientByCliIdClient;
    }
    public SousCategorieProduit getSousCategorieProduit() {
        return this.sousCategorieProduit;
    }
    
    public void setSousCategorieProduit(SousCategorieProduit sousCategorieProduit) {
        this.sousCategorieProduit = sousCategorieProduit;
    }
    public Client getClientByIdClient() {
        return this.clientByIdClient;
    }
    
    public void setClientByIdClient(Client clientByIdClient) {
        this.clientByIdClient = clientByIdClient;
    }
    public String getDesignationProduit() {
        return this.designationProduit;
    }
    
    public void setDesignationProduit(String designationProduit) {
        this.designationProduit = designationProduit;
    }
    public float getPrixProduit() {
        return this.prixProduit;
    }
    
    public void setPrixProduit(float prixProduit) {
        this.prixProduit = prixProduit;
    }
    public Date getDateMiseEnVenteProduit() {
        return this.dateMiseEnVenteProduit;
    }
    
    public void setDateMiseEnVenteProduit(Date dateMiseEnVenteProduit) {
        this.dateMiseEnVenteProduit = dateMiseEnVenteProduit;
    }
    public String getDescriptionProduit() {
        return this.descriptionProduit;
    }
    
    public void setDescriptionProduit(String descriptionProduit) {
        this.descriptionProduit = descriptionProduit;
    }




}


