package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private Integer idRegion;
     private Pays pays;
     private String nomRegion;
     private String codeRegion;
     private Set departements = new HashSet(0);

    public Region() {
    }

	
    public Region(Pays pays, String nomRegion, String codeRegion) {
        this.pays = pays;
        this.nomRegion = nomRegion;
        this.codeRegion = codeRegion;
    }
    public Region(Pays pays, String nomRegion, String codeRegion, Set departements) {
       this.pays = pays;
       this.nomRegion = nomRegion;
       this.codeRegion = codeRegion;
       this.departements = departements;
    }
   
    public Integer getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(Integer idRegion) {
        this.idRegion = idRegion;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }
    public String getNomRegion() {
        return this.nomRegion;
    }
    
    public void setNomRegion(String nomRegion) {
        this.nomRegion = nomRegion;
    }
    public String getCodeRegion() {
        return this.codeRegion;
    }
    
    public void setCodeRegion(String codeRegion) {
        this.codeRegion = codeRegion;
    }
    public Set getDepartements() {
        return this.departements;
    }
    
    public void setDepartements(Set departements) {
        this.departements = departements;
    }




}


