package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * SousCategorieProduit generated by hbm2java
 */
public class SousCategorieProduit  implements java.io.Serializable {


     private Integer idSousCategorieProduit;
     private CategorieProduit categorieProduit;
     private String sousCategorieProduit;
     private Set produits = new HashSet(0);

    public SousCategorieProduit() {
    }

	
    public SousCategorieProduit(CategorieProduit categorieProduit, String sousCategorieProduit) {
        this.categorieProduit = categorieProduit;
        this.sousCategorieProduit = sousCategorieProduit;
    }
    public SousCategorieProduit(CategorieProduit categorieProduit, String sousCategorieProduit, Set produits) {
       this.categorieProduit = categorieProduit;
       this.sousCategorieProduit = sousCategorieProduit;
       this.produits = produits;
    }
   
    public Integer getIdSousCategorieProduit() {
        return this.idSousCategorieProduit;
    }
    
    public void setIdSousCategorieProduit(Integer idSousCategorieProduit) {
        this.idSousCategorieProduit = idSousCategorieProduit;
    }
    public CategorieProduit getCategorieProduit() {
        return this.categorieProduit;
    }
    
    public void setCategorieProduit(CategorieProduit categorieProduit) {
        this.categorieProduit = categorieProduit;
    }
    public String getSousCategorieProduit() {
        return this.sousCategorieProduit;
    }
    
    public void setSousCategorieProduit(String sousCategorieProduit) {
        this.sousCategorieProduit = sousCategorieProduit;
    }
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }




}


