package fr.oh.entities;
// Generated 18 mai 2016 11:27:53 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ville generated by hbm2java
 */
public class Ville extends AbstractEntity implements java.io.Serializable {


     private Integer idVille;
     private Departement departement;
     private String nomVille;
     private float latitudeVille;
     private float longitudeVille;
     private String cpVille;
     private Set clients = new HashSet(0);

    public Ville() {
    }

	
    public Ville(Departement departement, String nomVille, float latitudeVille, float longitudeVille, String cpVille) {
        this.departement = departement;
        this.nomVille = nomVille;
        this.latitudeVille = latitudeVille;
        this.longitudeVille = longitudeVille;
        this.cpVille = cpVille;
    }
    public Ville(Departement departement, String nomVille, float latitudeVille, float longitudeVille, String cpVille, Set clients) {
       this.departement = departement;
       this.nomVille = nomVille;
       this.latitudeVille = latitudeVille;
       this.longitudeVille = longitudeVille;
       this.cpVille = cpVille;
       this.clients = clients;
    }
   
    public Integer getIdVille() {
        return this.idVille;
    }
    
    public void setIdVille(Integer idVille) {
        this.idVille = idVille;
    }
    public Departement getDepartement() {
        return this.departement;
    }
    
    public void setDepartement(Departement departement) {
        this.departement = departement;
    }
    public String getNomVille() {
        return this.nomVille;
    }
    
    public void setNomVille(String nomVille) {
        this.nomVille = nomVille;
    }
    public float getLatitudeVille() {
        return this.latitudeVille;
    }
    
    public void setLatitudeVille(float latitudeVille) {
        this.latitudeVille = latitudeVille;
    }
    public float getLongitudeVille() {
        return this.longitudeVille;
    }
    
    public void setLongitudeVille(float longitudeVille) {
        this.longitudeVille = longitudeVille;
    }
    public String getCpVille() {
        return this.cpVille;
    }
    
    public void setCpVille(String cpVille) {
        this.cpVille = cpVille;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


